import type { Course } from "./types";

function lit(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function json(value: unknown): string {
  return value === undefined || value === null ? "null" : `${lit(JSON.stringify(value))}::jsonb`;
}

function textArray(values: string[]): string {
  return `array[${values.map(lit).join(", ")}]::text[]`;
}

/** Idempotent SQL seed for the catalog: upserts courses, modules, lessons and interactions. */
export function buildSeedSql(courses: Course[]): string {
  const lines: string[] = [
    "-- Generated by scripts/generate-seed.ts, do not edit by hand.",
    "begin;",
  ];
  for (const c of courses) {
    lines.push(
      `insert into public.courses (id, slug, title, subtitle, description, category, level, price_cents, currency, stripe_price_id, theme, glyph, instructor, outcomes, published, featured, position)
values (${[lit(c.id), lit(c.slug), lit(c.title), lit(c.subtitle), lit(c.description), lit(c.category), lit(c.level), lit(c.priceCents), lit(c.currency), lit(c.stripePriceId), lit(c.theme), lit(c.glyph), json(c.instructor), textArray(c.outcomes), lit(c.published), lit(c.featured), lit(c.position)].join(", ")})
on conflict (id) do update set slug = excluded.slug, title = excluded.title, subtitle = excluded.subtitle, description = excluded.description, category = excluded.category, level = excluded.level, price_cents = excluded.price_cents, theme = excluded.theme, glyph = excluded.glyph, instructor = excluded.instructor, outcomes = excluded.outcomes, featured = excluded.featured, position = excluded.position;`,
    );
    for (const m of c.modules) {
      lines.push(
        `insert into public.modules (id, course_id, title, position) values (${lit(m.id)}, ${lit(c.id)}, ${lit(m.title)}, ${m.position})
on conflict (id) do update set title = excluded.title, position = excluded.position;`,
      );
      for (const l of m.lessons) {
        lines.push(
          `insert into public.lessons (id, course_id, module_id, slug, title, summary, duration_seconds, bunny_video_id, is_preview, position, chapters, takeaways, exercise)
values (${[lit(l.id), lit(c.id), lit(m.id), lit(l.slug), lit(l.title), lit(l.summary), lit(l.durationSeconds), lit(l.bunnyVideoId), lit(l.isPreview), lit(l.position), json(l.chapters), textArray(l.takeaways), lit(l.exercise)].join(", ")})
on conflict (id) do update set slug = excluded.slug, title = excluded.title, summary = excluded.summary, duration_seconds = excluded.duration_seconds, is_preview = excluded.is_preview, position = excluded.position, chapters = excluded.chapters, takeaways = excluded.takeaways, exercise = excluded.exercise;`,
        );
        for (const i of l.interactions) {
          lines.push(
            `insert into public.lesson_interactions (id, lesson_id, at_seconds, type, prompt, options, explanation, body, scale, xp, required)
values (${[lit(i.id), lit(l.id), lit(i.atSeconds), lit(i.type), lit(i.prompt), json(i.options), lit(i.explanation), lit(i.body), json(i.scale), lit(i.xp), lit(i.required)].join(", ")})
on conflict (id) do update set at_seconds = excluded.at_seconds, type = excluded.type, prompt = excluded.prompt, options = excluded.options, explanation = excluded.explanation, body = excluded.body, scale = excluded.scale, xp = excluded.xp, required = excluded.required;`,
          );
        }
      }
    }
  }
  lines.push("commit;", "");
  return lines.join("\n");
}
