/**
 * Single icon family for the whole product: Phosphor (regular weight).
 * The SSR entry works in both Server and Client Components.
 */
export {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  CaretDown,
  CaretLeft,
  Faders,
  ShareFat,
  MapPin,
  CalendarBlank,
  Medal as Award,
  ChartBar as BarChart3,
  BookOpen,
  BookOpenText as BookOpenCheck,
  Brain,
  Check,
  CheckCircle as CheckCircle2,
  Clock,
  Compass,
  CreditCard,
  CurrencyDollar as DollarSign,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FastForward,
  Fire as Flame,
  GraduationCap,
  SquaresFour as LayoutDashboard,
  Lightbulb,
  Lock,
  SignOut as LogOut,
  Envelope as Mail,
  EnvelopeOpen as MailCheck,
  CornersOut as Maximize,
  List as Menu,
  ChatCircle as MessageCircle,
  Microscope,
  CornersIn as Minimize,
  NotePencil as NotebookPen,
  Pause,
  PencilLine as PenLine,
  Play,
  PlayCircle,
  Printer,
  Receipt,
  ArrowCounterClockwise as RotateCcw,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  ShieldCheck as Shield,
  SkipForward,
  Sliders as SlidersHorizontal,
  Sparkle as Sparkles,
  Target,
  User as UserRound,
  Users,
  SpeakerHigh as Volume2,
  SpeakerSlash as VolumeX,
  X,
  Sun,
  Moon,
  Star,
  Lightning,
  Path,
  Cards,
  Footprints,
  Books,
  Infinity as InfinityIcon,
  SealCheck,
  Trophy,
  Flag,
  Heart,
  Plus,
} from "@phosphor-icons/react/dist/ssr";
export type { Icon as IconType } from "@phosphor-icons/react";
